### ISSUE TITLE
Error in readdir operation for directories with large file counts

### ISSUE THREAD

**Issue by WinBeyond** [adam900710/btrfs-fuse#11]
# An error occurred in readdir

## Description

The root directory contains approximately 100,000 files. When calling `readdir`, the operation fails with an error. Below are the operation logs and error details:

### Logs
```
getattr[NULL] /9993306.txt
unique: 13951, opcode: INTERRUPT (36), nodeid: 0, insize: 48, pid: 0
INTERRUPT: 13950
```

## Problem Description
- When a directory contains a large number of files (around 100,000), the `readdir` operation gets interrupted.
- The system log shows an `INTERRUPT (36)` error, and subsequent operations cannot continue.
- The issue may be related to high concurrency or the large number of files in the directory.

## Steps to Reproduce
1. Create a directory with approximately 100,000 files.
2. Use `readdir` or similar tools (e.g., `ls`) to read the directory.
3. Observe if the `INTERRUPT` error occurs.

## Expected Behavior
The `readdir` operation should successfully return the contents of the directory, even if it contains a large number of files.

## Actual Behavior
- The operation is interrupted, and the `INTERRUPT` error occurs.
- It is not possible to fully list the directory contents.

## Possible Causes
1. **High concurrency or timeout**: The large number of files in the directory may cause timeouts or resource exhaustion.
2. **FUSE implementation limitation**: The FUSE layer may encounter bottlenecks when processing large directories.
3. **File system limitations**: The file system might not be optimized for handling such large directories.

## Suggested Solutions
1. **Optimize directory structure**: Split large directories into multiple subdirectories to reduce the number of files per directory.
2. **Increase timeout**: Adjust the application or system settings to allow more time for operations to complete.
3. **Batch processing**: Process directory contents in batches to reduce the load on the `readdir` operation.
4. **Enable debug logging**: Use detailed logging to analyze the issue further:
   ```bash
   btrfs-fuse -d /dev/loop0 /mnt

**Comment by adam900710** [comment]
It's indeed a limitation in the `readdir` implementation of this project.
(The FUSE interface provides a way to handle it)

The problem is related to the handling of `filler` parameter to `btrfs_fuse_readdir()`.

Although I initially did honor the `offset` parameter, I didn't pass it into the filler function.
Thus the whole directory is read in one go, causing too much memory usage thus eventually cause problems.

I'll update the filler usage correpspondingly.

Thanks for spotting this bug.

**Comment by adam900710** [comment]
Mind to give it a try on the latest master branch?

In my local test environment it properly resume from the last found directory entry, thus it should be able to handle huge directory now.

**Comment by WinBeyond** [comment]
Sorry for responding so late, I have tried to use the master branch code to compile and run, but there is still a problem,and the error log is different. @adam900710 

```
getattr[NULL] /file3.txt
unique: 15, opcode: INTERRUPT (36), nodeid: 0, insize: 48, pid: 0
INTERRUPT: 14
User defined signal 1
```

The code below is my test code:

```golang

func main() {
    // Directory path to read
    dirPath := "./your_directory"

    // Open the directory
    f, err := os.Open(dirPath)
    if err != nil {
        log.Fatalf("Failed to open directory: %v", err)
    }
    defer f.Close()

    // Number of items to read per batch
    batchSize := 1000

    for {
        // Readdir(batchSize) reads up to batchSize FileInfo entries from the directory
        fileInfos, err := f.Readdir(batchSize)
        if err != nil {
            // If it's EOF, we've reached the end of the directory
            if err == io.EOF {
                break
            }
            // Otherwise, log the error and exit
            log.Fatalf("Failed to read directory entries: %v", err)
        }

        // Process the FileInfo entries
        for _, fi := range fileInfos {
            if fi.IsDir() {
                fmt.Printf("[Folder] %s\n", fi.Name())
            } else {
                fmt.Printf("[File]   %s\n", fi.Name())
            }
        }

        // If we got fewer entries than batchSize, we've reached the end
        if len(fileInfos) < batchSize {
            break
        }
    }

    fmt.Println("Reading complete!")
}

```

**Comment by adam900710** [comment]
This means the program got user signal 1 and interrupted.
I'm not sure why/who sent the signal.

Is there any dmesg of things like OOM triggering? And do you have any thing monitoring the memory usage of `btrfs-fuse`?
My current guess is, OOM got triggered.

**Comment by WinBeyond** [comment]
I can confirm that this is related to the programming language. Using golang's Readdir will indeed cause interruption-like problems, but using C language's readdir can list all files. Maybe it is caused by too much metadata information being obtained in golang. Here I Will use cgo to call C language code to avoid this problem
