### ISSUE TITLE
Possibility of read/write with transparent compression

### ISSUE THREAD

**Issue by ruanformigoni** [adam900710/btrfs-fuse#8]
Hey there,

I want to modify the project to support writing with the transparent compression aspect, do you think that it would be feasible?

Thanks.

**Comment by adam900710** [comment]
For write, compression is the least thing you need to bother.

The write path needs a lot of things like delayed-ref infrastructure.

My current objective is to make the code base small and mostly for bootloader port.

Thus write is not a high priority.


If you really want to implement the write support, I'd say you can go porting the btree COW code first, then delayed-refs, and the extent reservation part first.
But overall my estimation is, the write path would be 3x the number of lines, thus not really worthy.

**Comment by ruanformigoni** [comment]
Thanks for the pointers. I'll give it a shot :)
